export default [
  'The early bird catches the worm.',
  'A stitch in time saves nine.',
  'Actions speak louder than words.',
  'An apple a day keeps the doctor away.',
  'A penny saved is a penny earned.',
  'Beauty is in the eye of the beholder.',
  'Better late than never.',
  'Birds of a feather flock together.',
  'Cleanliness is next to godliness.',
  "Don't bite the hand that feeds you.",
  "Don't count your chickens before they hatch.",
  'Easy come, easy go.',
  'Every cloud has a silver lining.',
  'Fortune favors the bold.',
  'God helps those who help themselves.',
  'Good things come to those who wait.',
  'Honesty is the best policy.',
  'Hope for the best, prepare for the worst.',
  "If it ain't broke, don't fix it.",
  'Ignorance is bliss.',
  "It's never too late to mend.",
  'Laughter is the best medicine.',
  'Look before you leap.',
  'Lost time is never found again.',
  'Love all, trust a few, do wrong to none.',
  'Make hay while the sun shines.',
  'Necessity is the mother of invention.',
  'No man is an island.',
  'Not all that glitters is gold.',
  'Old habits die hard.',
  'Opportunity seldom knocks twice.',
  'Patience is a virtue.',
  'Practice makes perfect.',
  "Rome wasn't built in a day.",
  'Silence is golden.',
  'Slow and steady wins the race.',
  'The best things in life are free.',
  'The grass is always greener on the other side.',
  'The pen is mightier than the sword.',
  "There's no place like home.",
  'Time is money.',
  'To err is human; to forgive, divine.',
  'Two heads are better than one.',
  'When in Rome, do as the Romans do.',
  "Where there's smoke, there's fire.",
  "You can't have your cake and eat it too.",
  "You can't judge a book by its cover.",
  'You reap what you sow.',
  'Your guess is as good as mine.',
  'A rolling stone gathers no moss.',
];
